### ISSUE TITLE
Hi,How to get the map file \Bot\mmaps for TBC version 2.5?

### ISSUE THREAD

**Issue by bigofsmall** [DrewKestell/BloogBot#2]
Thanks in advance.

**Comment by DrewKestell** [comment]
I just uploaded a new .zip of all the mmaps for Vanilla and TBC here: https://drive.google.com/file/d/1PB-cmQSifb4WwdXFaK-yiAADlh7-qsq0/view?usp=sharing

You can find instructions on doing this yourself here: https://drewkestell.us/Article/6/Chapter/20

Simply use version 2.4.3 of the WoW client instead of 1.12.1.

**Comment by bigofsmall** [comment]
Hi,

I rund the command map-extractor.exe in BLIZZ server(TBC 2.5) not a privite server. But it seems that not working.

Thanks again.

**Comment by bigofsmall** [comment]
Hi,

Do you have any guide about navigation in retail?

Thanks a lot.

**Comment by DrewKestell** [comment]
I do not know of any.

**Comment by bigofsmall** [comment]
hi,
I have two question:
1) What about mapid? Is it always 0 or 1, as I found the file name are all begin with 000 or 001.
Or is it same as below with lua code in WOW?

/run local mapID = C_Map.GetBestMapForUnit("player"); print(format("You are in %s (%d)", C_Map.GetMapInfo(mapID).name, mapID))

2) is it possible that I download the mmaps files from your above google link, and then used it in retail since the version in retail is TBC 2.5. I can't sure if this is posible. 

Thanks&Regards

**Comment by bigofsmall** [comment]
So sorry for my type error , it should be **_classic TBC_** while not retail.
I can't sure if there's any difference between classic TBC and retail

**Comment by DrewKestell** [comment]
1. You can see the MapIds by digging around in the underlying data files in the WoW client. For example, I found a utility called [DBC Editor](https://www.mediafire.com/file/mmtyggkhwim/DBC_Editor.rar/file) that you can use to open and view the contents of the .dbc files. From there, you can open Map.dbc and see the MapIds:

![image](https://user-images.githubusercontent.com/6411339/126674574-91523b89-bee6-4a96-9d07-4bc16e8bb229.png)

It looks like somebody built a browser tool that has all the same info as well: https://wow.tools/dbc/?dbc=map&build=2.4.3.8606#page=1

2. No idea. I've never spent time reverse engineering the Classic WoW clients, so I don't know if they even use .dbc files anymore.
