### ISSUE TITLE
how to get warden scan offsets?

### ISSUE THREAD

**Issue by oiramario** [DrewKestell/BloogBot#4]
![image](https://user-images.githubusercontent.com/9280761/170559498-f13a2ce3-a4d7-4c1f-b6fc-e747f6ee2c3c.png)
cannot find any ref of offsets below. plz help.
```
WardenPageScanOffset = 0x00002B21;
WardenMemScanOffset = 0x00002A7F;
```
thanks for ur great work!

**Comment by DrewKestell** [comment]
You won't find those if you look for them in Cheat Engine (or equivalent program). The Warden module is sent from the server to the client at runtime, and the various scan functions aren't referenced by the game client via memory offset anywhere.

Read the conversation from [this thread on OwnedCore](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/328263-wow-1-12-1-5875-info-dump-thread-27.html). You can see the offsets listed there.

I believe folks got their hands on a compiled .dll of the Warden module, and others have reverse engineered it at the assembly level. I originally got these offsets from them. I have not reverse engineered Warden in depth, so my knowledge is mostly based off of what I've read on OwnedCore.

When I updated BloogBot to support TBC and WotLk (work in progress), I observed while debugging that these offsets remained consistent in all three versions of the game client. However, if you look at [this code](https://github.com/DrewKestell/BloogBot/blob/b71e8ded09ae97d8d6527bf34866d38530b1e7ce/BloogBot/WardenDisabler.cs#L170), you'll see the way I'm bootstrapping the Warden hook is different between all three. The client code that loads the Warden module from the server has changed slightly, but the Warden module itself seems to be consistent.

Hope this helps.
