### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by sikrinick** [DrewKestell/BloogBot#5]
Hi, thanks for the bot.

Unfortunately, links for the website in Readme do not work.

URL: https://drewkestell.us/
Error code: 403

<img width="778" alt="image" src="https://user-images.githubusercontent.com/13406895/175609141-f5f3509a-ee09-49a6-a823-a7dffef193b3.png">

**Comment by DrewKestell** [comment]
Sorry about that. Currently doing some maintenance on my web hosting infrastructure and things will be unstable for a bit. Hoping to have everything back up in early July. Thanks for the heads up.

**Comment by DrewKestell** [comment]
This has been resolved!
