### ISSUE TITLE
Document DB Schemas and create scripts

### ISSUE THREAD

**Issue by Pooch11** [DrewKestell/BloogBot#6]
Currently there is no indication of DB Schemas used within the project, even though `Repository.cs` makes calls to the DB during startup and it is difficult to deduce what fields are in each table and their respective datatypes.

The docs should provide entry-level SQL/MySQL script which would create the necessary tables and columns (and data types) needed to spin up the project.

So far I have encountered the following tables;
- hotspots (Id , Zone, Description, Faction, MinimumLevel, Waypoints ..)
- npcs
- blacklistedmobs
- travelpaths

TODO:
- [x] Enumerate Tables
- [x] Enumerate Fields & data types
- [x] Create SQL script to make the required tables programmatically  (these can be external snippets)

**Comment by DrewKestell** [comment]
This is a hobby project that I provide no official support for. Please feel free to create these scripts and submit a PR.

**Comment by Pooch11** [comment]
Still a WIP as far as Primary/Foreign keys and some datatype adjustments but these are the minimum requirements to get the project running without crashing upon startup due to unknown data bindings. There may also seems to be an indication that a SpellsDB table will be implemented in the future.


```
CREATE TABLE hotspots(
id int,
zone text,
description nvarchar(4000),
faction nvarchar(4000),
minimumLevel int,
waypoints nvarchar(4000),
innKeeper boolean,
innkeeperId int,
ammoVendor boolean,
ammoVendorId int,
repairVendor boolean,
repairVendorId int,
safeforGrinding boolean,
travelpathId int
);

CREATE TABLE blacklistedmobs(
id int,
name nvarchar(4000),
guid nvarchar(4000)
);

CREATE TABLE travelpaths(
id int,
name nvarchar(50),
waypoints nvarchar(4000)
);

CREATE TABLE commands (
id int,
player nvarchar(50),
command nvarchar(50),
args nvarchar(50)
);

CREATE TABLE reportsignatures(
id int,
player nvarchar(50),
commandId int
)

CREATE TABLE npcs (
id int,
name nvarchar(50),
isInnKeeper boolean,
sellsAmmo boolean,
repairs boolean,
quest boolean,
horde boolean,
alliance boolean,
positionx float,
positiony float,
positionz float,
zone text);
```

**Comment by Pooch11** [comment]
I was using this for vanilla, so be sure to look in `Repository.cs` file for any changes that could be called from the TBC version. I'm not aware. 
That's where I derived the SQL statements to tables.
As far as the conversion to MySQL to AzureMS SQL that looks like the right (and most agreed upon) approach, you could add a `default 0` perhaps. Otherwise try tinyint(1)

![image](https://user-images.githubusercontent.com/5437388/204986108-ddce5d5f-939f-415c-885c-bb00d02a4b39.png)


Were the tables created in your database with no errors? Do they exist? The Exception you're getting has to do with the number of columns or the name, I'm not sure about the typing.  🤔 

My bootstrapper also starts to work, but fails under certain class loads/conditions. It also fails to load the player, I suspect from the spells ID table which is needs to be populated. Other times its a lot of warden spam, but that may be a different issue all together due to different clients

**Comment by DrewKestell** [comment]
Hey guys, I'm going to try to take a look at this over the weekend. I just created a Discord server to make it easier for folks to coordinate if you want to make contributions - feel free to join [here](https://discord.gg/S4tvykaGcJ).

**Comment by DrewKestell** [comment]
Thanks for the work on this guys. I added a script "SqlSchema.SQL" to the repo root that will create all table dependencies. You should be able to use either Azure SQL, or a local install of SQL.
