### ISSUE TITLE
Bug: Frost Mage Combat State uses an invalid spell.

### ISSUE THREAD

**Issue by ericbfriday** [DrewKestell/BloogBot#8]
Currently, a bot will use Frostbolt as the fallback damage dealing spell when Frost Mage is selected. However, with a fresh character they can make it to level 8 in a small amount of time and may not have trained the spell. Combat state does not cast any known spells in this case, causing a death loop.

Fix PR: #7 

Tested on WoW Client Version: Vanilla (server is mangos-based).

**Comment by DrewKestell** [comment]
Thanks for fixing this :)
